DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS shops;