// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       int32
	ShopID   int32
	Name     string
	ParentID pgtype.Int4
}

type Channel struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Conversation struct {
	ID        int32
	SessionID int32
	Message   string
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Order struct {
	ID        int32
	ShopID    int32
	UserID    pgtype.Int4
	Total     pgtype.Numeric
	Status    pgtype.Text
	CreatedAt pgtype.Timestamp
}

type OrderItem struct {
	ID        int32
	OrderID   int32
	ProductID pgtype.Text
	Quantity  int32
	UnitPrice pgtype.Numeric
}

type Product struct {
	ID          string
	ShopID      int32
	CategoryID  pgtype.Int4
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
	Stock       pgtype.Int4
	CreatedAt   pgtype.Timestamp
}

type Role struct {
	ID   int32
	Name string
}

type Session struct {
	ID        int32
	UserID    int32
	ChannelID int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Shop struct {
	ID            int32
	Name          string
	Description   string
	LogoUrl       pgtype.Text
	WebsiteUrl    pgtype.Text
	Email         pgtype.Text
	WhatsappPhone pgtype.Text
	Address       string
	City          string
	State         string
	ZipCode       string
	Country       string
	Latitude      float64
	Longitude     float64
	IsActive      bool
	Slug          pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID               int32
	ShopID           int32
	Email            pgtype.Text
	UnconfirmedEmail pgtype.Text
	Phone            pgtype.Text
	UnconfirmedPhone pgtype.Text
	IsActive         pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Slug             pgtype.UUID
}

type UserProfile struct {
	UserID     int32
	Phone      pgtype.Text
	FirstName  pgtype.Text
	LastName   pgtype.Text
	Address    pgtype.Text
	City       pgtype.Text
	Country    pgtype.Text
	PostalCode pgtype.Text
}

type UserRole struct {
	UserID int32
	RoleID int32
}
