// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (shop_id, user_id, total, status)
VALUES ($1, $2, $3, $4)
RETURNING id, shop_id, user_id, total, status, created_at
`

type CreateOrderParams struct {
	ShopID int32
	UserID pgtype.Int4
	Total  pgtype.Numeric
	Status pgtype.Text
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ShopID,
		arg.UserID,
		arg.Total,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.Total,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getListOrders = `-- name: GetListOrders :many
SELECT id, shop_id, user_id, total, status, created_at
FROM orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetListOrdersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetListOrders(ctx context.Context, arg GetListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getListOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.UserID,
			&i.Total,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, shop_id, user_id, total, status, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.Total,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET total = $2, status = $3
WHERE id = $1
RETURNING id, shop_id, user_id, total, status, created_at
`

type UpdateOrderParams struct {
	ID     int32
	Total  pgtype.Numeric
	Status pgtype.Text
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.ID, arg.Total, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.Total,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
