// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_login_otp.sql

package db

import (
	"context"
)

const insertUserLoginOtp = `-- name: InsertUserLoginOtp :exec
INSERT INTO user_login_otp (user_id, otp)
VALUES ($1, $2)
`

type InsertUserLoginOtpParams struct {
	UserID int32
	Otp    string
}

func (q *Queries) InsertUserLoginOtp(ctx context.Context, arg InsertUserLoginOtpParams) error {
	_, err := q.db.Exec(ctx, insertUserLoginOtp, arg.UserID, arg.Otp)
	return err
}
